# Generated by Django 3.2.5 on 2021-07-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210726_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': False},
        ),
    ]
