# Generated by Django 3.2.5 on 2021-08-13 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
