# Generated by Django 3.2.5 on 2021-07-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
