# Generated by Django 3.2.5 on 2021-08-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.ImageField(blank=True, default='https://wallpapercave.com/wp/wp7264190.jpg', null=True, upload_to='user_backgrounds'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='https://image.flaticon.com/icons/png/512/149/149071.png', null=True, upload_to='user_photos'),
        ),
    ]
