# Generated by Django 3.2.5 on 2021-08-06 21:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wall', '0004_observe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('observe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observe', to=settings.AUTH_USER_MODEL)),
                ('observed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Observe',
        ),
    ]
