# Generated by Django 3.2.5 on 2021-08-13 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0006_auto_20210808_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='reciver',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
